apiVersion: v2
name: chart-livia
description: Meu Primeira chart - treimamento Kubernetes 
type: application
version: 0.1.0
appVersion: "1.16.0"

#http or file

icon: https://thumbs.dreamstime.com/b/nginx-icon-logo-142469461.jpg